name: Publish Docker Image

on:
  push:
    branches:
      - master
      - minecraft*

    # Publish minecraft version tags (eg `m1.16.4`) as releases.
    tags:
      - m*

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate image tags
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: |
            spaceface16518/minecraft
            ghcr.io/Spaceface16518/minecraft
          tag-match: '\d{1,3}\.\d{1,3}\.\d{1,3}'
          tag-match-group: 0 # tag using minecraft version, not image version
          tag-match-latest: true
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
